# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Big Hero
  description: Main page Hero block
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""
  postheading: ""
  background_image: ""
  link_main:
    text: ""
    url: ""
  link_secondary:
    text: ""
    url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: Material Handling as a Service for logistics and industrial companies
  postheading: With our proprietary technology, we are helping to tackle employee shortages and improve material handling throughput in any type of environment.
  background_image: /images/bg/home-1.jpg
  link_main:
    text: "Learn more"
    url: ""
  link_secondary:
    text: "Contact us"
    url: ""

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
