baseURL = 'https://ivailieva.github.io/'
languageCode = 'en-us'
title = 'Iva Ilieva Blog'
theme = "megakit-hugo-template"

[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'