# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: 
  description: Description section
  icon: send_to_mobile
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  header: ""
  text: ""


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheading: 
  heading: 
  header: 
  text: 
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
